# Generated by Django 3.2.25 on 2025-12-26 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petition_id', models.CharField(max_length=32, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('requiere_rele', models.BooleanField(default=False)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('foto_receta', models.ImageField(blank=True, null=True, upload_to='formulas/recetas/')),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('EN_PREPARACION', 'En Preparación'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='RECIBIDA', max_length=20)),
                ('fecha_preparacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('notas_laboratorio', models.TextField(blank=True)),
                ('preparado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulas_preparadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
